language: node_js
services:
    - docker
node_js:
    - lts/*
cache:
    npm: false
    directories:
    - "~/.pnpm-store"
before_install:
    - curl -L https://unpkg.com/@pnpm/self-installer | node
    - pnpm config set store-dir ~/.pnpm-store
    - sudo apt-get update
    - sudo apt-get -y install jq
    - if [ -n "$DOCKER_PASSWORD" ]; then docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"; fi
    - docker build -t binaryfissiongames/your-broadcasting-suite-client -f backend/Dockerfile .
    - docker build -t binaryfissiongames/your-broadcasting-suite-client -f frontend/Dockerfile .
    - docker run -dp 80:80 binaryfissiongames/your-broadcasting-suite-client
    - docker ps -a
    - curl http://127.0.0.1/index.html

script:
    - pnpm run lint-no-fix -r
    - pnpm run check-pretty -r
    - pnpm run build-test -r
    - pnpm run test -r

after_success:
    - if [ -n "$DOCKER_PASSWORD" ]; then chmod 777 ./backend/dockerPush.sh && ./backend/dockerPush.sh && chmod 777 ./frontend/dockerPush.sh && ./frontend/dockerPush.sh; fi
