apiVersion: v1
kind: ConfigMap
metadata:
  name: api-server-config-{{ .Release.Name }}
data:
  env: {{ .Values.env }}
  twitch_client_id: {{ .Values.twitchClientId }}
  oauth_redirect_uri: https://{{ .Values.apiHostName }}/auth/login
  host_name: https://{{ .Values.apiHostName }}:{{ .Values.apiPortHttps }}
  webhook_lease_in_seconds: "864000"
  client_application_url: https://{{ .Values.clientHostName }}
  allowed_origins: https://{{ .Values.clientHostName }}
  mock_hub_url: http://localhost:4080/hub
  mock_auth_url: http://{{ .Values.mockAuthHostName }}/authorize
  mock_token_url: http://localhost:5080/token
  mock_validate_url: http://localhost:5080/oauth2/validate
