apiVersion: v1
kind: Service
metadata:
  name: api-mock-webhook-server-service-{{ .Release.Name }}
  labels:
    app: YourBroadcastingSuiteAPIServer
spec:
  ports:
    - name: http
      port: 4080
      targetPort: 4080
  selector:
    app: YourBroadcastingSuiteAPIServer
