apiVersion: v1
kind: Secret
metadata:
  name: api-server-secret-{{ .Release.Name }}
type: Opaque
data:
  twitch_client_secret: {{ .Values.twitchClientSecret | b64enc }}
  session_secret: {{ .Values.sessionSecret | b64enc }}
  database_connect_url: {{ printf "mysql://%v:%v@%v:%v/%v" .Values.mysqlUser .Values.mysqlPassword .Values.mysqlServiceName .Values.mysqlPort .Values.mysqlDatabase | b64enc }}
  redis_connect_url: {{ printf "redis://:%v@%v%v:%v/%v" .Values.redis.password .Release.Name .Values.redisHostSuffix .Values.redis.redisPort .Values.redisDatabase | b64enc }}
