apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: api-mock-webhook-ingress-{{ .Release.Name }}
  labels:
    app: YourBroadcastingSuite
spec:
  tls:
    - hosts:
        - {{ .Values.mockWebhookHostName }}
        {{- range .Values.extraMockWebhookHostNames }}
        - {{ . }}
        {{- end }}
      secretName: cert-{{ .Release.Name }}-api-secret
  rules:
    - host: {{ .Values.mockWebhookHostName }}
      http:
        paths:
          - backend:
              serviceName: api-mock-webhook-server-service-{{ .Release.Name }}
              servicePort: 4080
status:
  loadBalancer:
    ingress:
      - hostname: {{ .Values.mockWebhookHostName }}
