apiVersion: v1
kind: Service
metadata:
  name: api-mock-auth-server-service-{{ .Release.Name }}
  labels:
    app: YourBroadcastingSuiteAPIServer
spec:
  ports:
    - name: http
      port: 5080
      targetPort: 5080
  selector:
    app: YourBroadcastingSuiteAPIServer
