apiVersion: v1
kind: Service
metadata:
  name: api-server-service-{{ .Release.Name }}
  labels:
    app: YourBroadcastingSuiteAPIServer
spec:
  ports:
    - name: http
      port: {{ .Values.apiPortHttp }}
      targetPort: {{ .Values.apiPortHttp }}
  selector:
    app: YourBroadcastingSuiteAPIServer
