apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-server-deployment-{{ .Release.Name }}
  labels:
    app: YourBroadcastingSuite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: YourBroadcastingSuiteClientServer
  template:
    metadata:
      labels:
        app: YourBroadcastingSuiteClientServer
    spec:
      containers:
        - name: your-broadcasting-suite-client-server
          image: {{ .Values.clientServerImage }}
          imagePullPolicy: Never
          ports:
            - containerPort: 443
              name: http
          readinessProbe:
            httpGet:
              path: /
              port: 443
            initialDelaySeconds: 30
            periodSeconds: 15
            failureThreshold: 10
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 443
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 5
