apiVersion: batch/v1
kind: Job
metadata:
  name: database-migrations
spec:
  template:
    spec:
      containers:
      - name: database-migrations
        image: your-broadcasting-suite-dev:0.0.1
        command: ["npm",  "run", "migrate"]
        imagePullPolicy: Never
        env:
          - name: NODE_ENV
            valueFrom:
              configMapKeyRef:
                name: api-server-config-your-broadcasting-suite
                key: env
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: api-server-secret-your-broadcasting-suite
                key: database_connect_url
      restartPolicy: Never
  backoffLimit: 5
