name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Setup PNPM
      uses: pnpm/action-setup@v1.2.0
      with:
        version: 5.13.4
        run_install: true
    - run: pnpm recursive lint --if-present
    - run: pnpm run test --if-present
    #TODO: Build & test docker containers.
