name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Setup PNPM
      uses: pnpm/action-setup@v1.2.1
      with:
        version: 5.13.5
    - run: pnpm recursive exec -- pnpm run lint --if-present
    - run: pnpm recursive exec -- pnpm run check-pretty --if-present
    # Build & test docker containers
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build backend
      id: docker_build_0
      uses: docker/build-push-action@v2
      with:
        push: false
        file: ./backend/Dockerfile
    - name: Build frontend
      id: docker_build_1
      uses: docker/build-push-action@v2
      with:
        push: false
        file: ./backend/Dockerfile
